### ISSUE TITLE
Call to undefined function resource_path()

### ISSUE THREAD

**Issue by ChugunovRoman** [artem328/laravel-yandex-kassa#2]
PHP Fatal error:  Call to undefined function Artem328\\LaravelYandexKassa\\resource_path() in /home/sites/kkt365ru/www/vendor/artem328/laravel-yandex-kassa/src/LaravelYandexKassa/YandexKassaServiceProvider.php on line 31

Как я понял, функция resource_path() возвращает путь до каких-то ресурсов? Что за ресурсы и где они должны быть? И где объявлена эта функция?

**Comment by artem328** [comment]
Это функция helper фреймворка Laravel. [Здесь](https://laravel.com/docs/5.4/helpers#method-resource-path) можно почитать о ней.

Данная ошибка может возникнуть если файл с функциями Ларавела не подключился по-какой либо причине.

**Comment by ChugunovRoman** [comment]
Но остальные функции хелперы (app_path(), base_path(), config_path() и т.д.) работают. Похоже, что эту функцию добавили в более позднюю версию. А может в October'е laravel немного модифицированный, и они убрали такую функцию или заменили на свою. Папки "resource" в корне нету. Если смотреть на чистый laravel, то у него в корне есть эта папка. И похоже на нее и ссылается функция resource_path(). 
Посмотрел я исходники laravel и сравнил.. С версии 5.2 была добавлена эта функция. 
У меня такая версия Laravel с October CMS идет:
```
php artisan --version
$ Laravel Framework version 5.1.45 (LTS)
```
Думаю обновить отдельно... если это возможно
