### ISSUE TITLE
Яндекс возвращает данные методом GET, а в пакете POST!?

### ISSUE THREAD

**Issue by fomvasss** [artem328/laravel-yandex-kassa#4]
Здравствуйте. Планирую использовать ваш пакет в своем проекте, для приема платежей через Яндекс.
Возникла проблема при возврате данных про оплату с Яндекса.
Как я увидел, в роутах пакета используется метод post (`$router->post()`) , а мне Яндекс возвращает ответ методом get. Ларавал показывает ошибку роута. Когда я в коде пакета меняю на get - работает! 
И вот еще в документации Яндекса прочитал: [Переход происходит методом GET (исключение — неуспех оплаты из кошелька в Яндекс.Деньгах, в этом случае переход происходит методом POST).](https://tech.yandex.ru/money/doc/payment-solution/shop-config/parameters-docpage/)
Может я что-то не правильно понял или пропустил? Или все же, нужно сделать на метод get, или добавить возможность менять в конфигах?

**Comment by artem328** [comment]
Думаю, что мой ответ уже не актуален. 

И пакет, я, не поддерживаю уже давно.
